// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3N_sUMlBZ_ID6a7OmXU7vmTZinURth34',
    appId: '1:1011317361829:web:eaddb952fce52b48a9114c',
    messagingSenderId: '1011317361829',
    projectId: 'parkin-campus',
    authDomain: 'parkin-campus.firebaseapp.com',
    storageBucket: 'parkin-campus.firebasestorage.app',
    measurementId: 'G-MGV93PGBN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxtSPE5MCQTvc_RNVZrGZGhkPjhC1skCw',
    appId: '1:1011317361829:android:8dc558076d639815a9114c',
    messagingSenderId: '1011317361829',
    projectId: 'parkin-campus',
    storageBucket: 'parkin-campus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd6JUDXHAMQdIQ-mV03hOyhdBJr_X8KmI',
    appId: '1:1011317361829:ios:98bdf797e5d92a44a9114c',
    messagingSenderId: '1011317361829',
    projectId: 'parkin-campus',
    storageBucket: 'parkin-campus.firebasestorage.app',
    iosBundleId: 'com.example.parkInCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd6JUDXHAMQdIQ-mV03hOyhdBJr_X8KmI',
    appId: '1:1011317361829:ios:98bdf797e5d92a44a9114c',
    messagingSenderId: '1011317361829',
    projectId: 'parkin-campus',
    storageBucket: 'parkin-campus.firebasestorage.app',
    iosBundleId: 'com.example.parkInCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3N_sUMlBZ_ID6a7OmXU7vmTZinURth34',
    appId: '1:1011317361829:web:dc4d6ac10a55fa1ea9114c',
    messagingSenderId: '1011317361829',
    projectId: 'parkin-campus',
    authDomain: 'parkin-campus.firebaseapp.com',
    storageBucket: 'parkin-campus.firebasestorage.app',
    measurementId: 'G-764X3MLXB8',
  );
}
